language: python
python:
  - 3.6.2

services:
  - docker
  - docker-compose

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - docker-compose -f docker-compose-prod.yml build

script:
  - docker-compose -f docker-compose-prod.yml run --rm web ./wait-for-it.sh db:5432 -- python3 manage.py test
  - docker-compose -f docker-compose-prod.yml run --rm web python3 -m pycodestyle --select=E302,E211,E202,E712,E225,E231 .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

