version: "2"

volumes:
  dbvolume:
  ipython:
  static_volume:
  torrent:

services:
  db:
    image: postgres:9.6.17
    env_file:
      - .env
    ports:
      - 5543:5432
    volumes:
      - dbvolume:/var/lib/postgresql/data/
  
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    restart: always
    ports:
      - 8000:8000
      - 9091:9091
    env_file:
      - .env
    environment:
      - DEPLOY_ENV=production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - HTTPSTREAMING_HOST=${HTTPSTREAMING_HOST}
    volumes:
      - ./Videos/:/usr/src/app/Videos
      - static_volume:/usr/static/
      - ipython:/root/.ipython
      - torrent:/usr/torrent/:rw
    command: bash -c "service transmission-daemon start && python3 /usr/src/app/manage.py collectstatic --no-input && gunicorn StreamingServer.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    volumes:
      - ./Videos/:/usr/src/app/Videos
      - static_volume:/usr/static/
      - torrent:/usr/torrent/:rw
    ports:
      - 80:80
    depends_on:
      - web

  celery:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    command: celery -A StreamingServer worker -l info
    volumes:
        - ./Videos/:/usr/src/app/Videos
        - torrent:/usr/torrent/:rw
    env_file:
        - .env
    environment:
      - DEPLOY_ENV=production
    depends_on:
        - db
        - redis

  redis:
    image: redis:alpine
    command: redis-server --port 6380
