version: "2"

volumes:
  ipython_volume:
  static_volume:
  node_modules_volume:

services:
  db:
    image: postgres:9.6
    ports:
      - 5543:5432
    env_file:
      - .env
    volumes:
      - /home/StreamServer/database:/var/lib/postgresql/data/
  
  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DEPLOY_ENV=dev
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - HTTPSTREAMING_HOST=${HTTPSTREAMING_HOST}
    volumes:
      - /home/StreamServer/Videos:/usr/src/app/Videos
      - /home/StreamServer/torrent:/usr/torrent/:rw
      - ./backend/:/usr/src/app/
      - static_volume:/usr/static/
      - ipython_volume:/root/.ipython
    command: bash -c "./wait-for-it.sh db:5432 -- python3 /usr/src/app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    volumes:
      - /home/StreamServer/Videos:/usr/src/app/Videos
      - /home/StreamServer/torrent:/usr/torrent/:rw
      - ./backend/:/usr/src/app/
      - ./nginx/nginx.conf /etc/nginx/conf.d/nginx.conf
      - static_volume:/usr/static/
    ports:
      - 80:80
    depends_on:
      - web

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/usr/src/app/
      - node_modules_volume:/usr/src/app/node_modules
    command: bash -c "npm start"
    depends_on:
      - web
    env_file:
      - .env
    ports:
      - 3000:3000

  celery:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A StreamingServer worker -l info
    volumes:
        - /home/StreamServer/Videos:/usr/src/app/Videos
        - /home/StreamServer/torrent:/usr/torrent/:rw
        - ./backend/:/usr/src/app/
    env_file:
        - .env
    depends_on:
        - db
        - redis

  celery_beat:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A StreamingServer beat -l info
    volumes:
      - /home/StreamServer/Videos:/usr/src/app/Videos
      - /home/StreamServer/torrent:/usr/torrent/:rw
      - ./backend/:/usr/src/app/
    env_file:
        - .env
    depends_on:
        - db
        - redis

  redis:
    image: redis:alpine
    command: redis-server --port 6380
    ports:
        - 6380:6380
