# Generated by Django 2.2.8 on 2022-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechRecognizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('access_key_id', models.CharField(max_length=100)),
                ('access_key_secret', models.CharField(max_length=100)),
                ('app_key', models.CharField(max_length=200)),
                ('oss_bucket_name', models.CharField(max_length=100)),
                ('oss_endpoint_domain', models.CharField(max_length=100)),
                ('oss_access_key_id', models.CharField(max_length=100)),
                ('oss_access_key_secret', models.CharField(max_length=200)),
            ],
        ),
    ]
