# Generated by Django 2.2.8 on 2023-02-01 09:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StreamServerApp', '0025_video_origin_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='md5',
            field=models.CharField(max_length=100),
        ),
    ]
